
INSERT INTO `participants` (`pid`, `firstname`, `lastname`, `region`, `commune`, `cluster`, `atelier`, `email`) VALUES
(1, 'michel', 'amaudruz', 'Lavaux', 'Le Mont-sur-Lausanne', 102, 6, ''),
(2, 'pascal', 'ansermet', 'Nyon', 'Chéserex', 13, 0, ''),
(3, 'marc', 'aubert', 'Morges', 'Pampigny', 3, 2, ''),
(4, 'olivier', 'augsburger', 'Broye - Vully', 'Bussy-sur-Moudon', 3, 0, ''),
(5, 'denis', 'baatard', 'Nord Vaudois', 'Chavannes-le-Chêne', 9, 0, NULL),
(6, 'charles', 'bachmann', 'Broye - Vully', 'Valbroye', 16, 7, NULL),
(7, 'philippe', 'bally', 'Joux', 'Vaulion', 10, 8, NULL),
(8, 'lucien', 'basset', 'Jura', 'Champagne', 2, 9, NULL),
(9, 'marc', 'benoit', 'Joux', 'Romainmôtier-Envy', 11, 6, NULL),
(10, 'claude-alain', 'berzin', 'Gros-de-Vaud', 'Montanaire', 5, 0, NULL),
(11, 'cédric', 'biedermann', 'Lavaux', 'Forel (Lavaux)', 5, 1, NULL),
(12, 'louis', 'blanchard', 'Gros-de-Vaud', 'Essertines-sur-Yverdon', 7, 1, NULL),
(13, 'michel', 'blanche', 'Chablais', 'Aigle', 1, 0, NULL),
(14, 'marcel', 'bonzon', 'Chablais', 'Aigle', 13, 0, NULL),
(15, 'stéphane', 'bolay', 'Morges', 'Pampigny', 5, 0, NULL),
(16, 'cédric', 'despont', 'Broye - Vully', 'Assens', 9, 0, NULL),
(17, 'samuel-georges', 'chapuis', 'Nord Vaudois', 'Champvent', 12, 4, NULL),
(18, 'bertrand', 'cheseaux', 'Chablais', 'Aigle', 9, 1, NULL),
(19, 'luc', 'chollet', 'Nyon', 'Nyon', 5, 3, NULL),
(20, 'christian', 'billaud', 'Nord Vaudois', 'Donneloye', 16, 0, NULL),
(21, 'claude', 'quillet', 'Nord Vaudois', '', 4, 0, NULL),
(22, 'claude-eric', 'gilliand', 'Gros-de-Vaud', 'Combremont-le-grand', 9, 0, NULL),
(23, 'marc-henri', 'pidoux-guex', 'Broye - Vully', 'Villars-le-Comte', 9, 0, NULL),
(24, 'sylvain', 'crausaz', 'Broye - Vully', 'Hermenches', 20, 0, NULL),
(25, 'jean-daniel', 'cruchet', 'Nord Vaudois', 'Giez', 9, 4, NULL),
(26, 'roger', 'cruchon', 'Morges', 'Lonay', 5, 2, NULL),
(27, 'adrien', 'david', 'Morges', 'Moiry', 8, 0, NULL),
(28, 'frederic', 'degeneve', 'Morges', 'Pampigny', 5, 2, NULL),
(29, 'philippe', 'devantay', 'Morges', 'Grancy', 15, 2, NULL),
(30, 'jean', 'duboux', 'Lavaux', 'Bourg-en-Lavaux', 3, 7, NULL),
(31, 'nicolas', 'dumauthioz', 'Morges', 'Pampigny', 5, 0, NULL),
(32, 'alain', 'dupertuis', 'Chablais', 'Aigle', 16, 1, NULL),
(33, 'christian', 'dupuis', 'Nyon', 'Perroy', 5, 3, NULL),
(34, 'stéphane', 'dutly', 'Broye - Vully', 'Payerne', 4, 0, NULL),
(35, 'alain', 'duvoisin', 'Jura', 'T?enon', 15, 9, NULL),
(36, 'philippe', 'dyens', 'Jura', 'Concise', 9, 4, NULL),
(37, 'eric', 'glauser', 'Gros-de-Vaud', 'Villars-le-Terroir', 9, 0, NULL),
(38, 'etienne', 'gonin', 'Broye-Vully', 'Essertines sur Yverdon', 5, 0, NULL),
(39, 'sidney', 'borgeaud', 'Morges', 'Gollion', 11, 0, NULL),
(40, 'sébastien', 'favre', 'Lavaux', 'Oron', 11, 6, NULL),
(41, 'pierre-alain', 'fiechter', 'Nord Vaudois', 'Bofflens', 16, 9, NULL),
(42, 'florian', 'tzaut', 'Broye - Vully', 'Bottens', 9, 0, NULL),
(43, 'françois', 'duc', 'Nord Vaudois', 'Granges-près-Marnand', 8, 0, NULL),
(44, 'frédéric', 'crausaz', 'Gros-de-Vaud', 'Chavannes sur Moudon', 16, 0, NULL),
(45, 'didier', 'frei', 'Nyon', 'Duillier', 10, 3, NULL),
(46, 'sylvain', 'freymond', 'Morges', 'Montricher', 9, 0, NULL),
(47, 'mathias', 'gaillard', 'Lavaux', 'Savigny', 7, 0, NULL),
(48, 'andré', 'galli', 'Gros-de-Vaud', 'Jorat-Menthue', 16, 7, NULL),
(49, 'jean-daniel', 'gamma', 'Jura', 'Bullet', 8, 9, NULL),
(50, 'eric', 'ginier', 'Enhaut', 'Ormont-Dessous', 16, 5, NULL),
(51, 'pierre-andré', 'golay', 'Joux', 'Le Chenit', 9, 8, NULL),
(52, 'jean-luc', 'guerry', 'Morges', 'Chevilly', 2, 0, NULL),
(53, 'beat', 'haenni', 'Jura', 'Provence', 2, 0, NULL),
(54, 'claude', 'henneberger', 'Gros-de-Vaud', 'Bottens', 5, 0, NULL),
(55, 'daniel', 'hofer', 'Nyon', 'Burtigny', 3, 0, NULL),
(56, 'andré', 'horisberger', 'Gros-de-Vaud', 'Bournens', 13, 0, NULL),
(57, 'philippe', 'humbert-girod', 'Jura', 'Corcelles-pr?-Concise', 1, 0, NULL),
(58, 'théophile', 'jaccoud', 'Joux', 'Le Chenit', 7, 8, NULL),
(59, 'christian-andré', 'salvisberg', 'Gros-de-Vaud', 'Bercher', 16, 4, NULL),
(60, 'yves', 'jaquiery', 'Nord Vaudois', 'Démoret', 12, 4, NULL),
(61, 'jean-claude', 'cherbuin', 'Nord Vaudois', 'Vers-chez-Perrin', 20, 0, NULL),
(62, 'philippe', 'jean-mairet', 'Broye-Vully', 'Grandcour', 1, 6, NULL),
(63, 'jean-pierre', 'widemer-zufferey', 'Nyon', '', 5, 0, NULL),
(64, 'jean-robert', 'kueffer', 'Nyon', 'Chéserex', 16, 3, NULL),
(65, 'pascal', 'lagnaz', 'Gros-de-Vaud', 'Pailly', 15, 4, NULL),
(66, 'laurent', 'doudin', 'Broye-Vully', 'Corcelles-près-Payerne', 5, 0, NULL),
(67, 'adrien', 'liechti', 'Nyon', 'Prangins', 15, 2, NULL),
(68, 'pierre', 'magnenat', 'Morges', 'Ferreyres', 11, 0, NULL),
(69, 'virginie', 'mastroianni', 'Lavaux', 'Savigny', 9, 1, NULL),
(70, 'pierre-alain', 'messeiller', 'Morges', 'Orny', 9, 0, NULL),
(71, 'roland', 'monge', 'Nord Vaudois', 'Donneloye', 9, 0, NULL),
(72, 'romain', 'monnard', 'Nyon', 'Mont-sur-Rolle', 7, 4, NULL),
(73, 'jean-luc', 'morier-genoud', 'Enhaut', 'Rougemont', 16, 5, NULL),
(74, 'nicolas', 'baud', 'Broye-Vully', 'Cudrefin', 11, 0, NULL),
(75, 'sébastien', 'oulevey', 'Broye - Vully', 'Grandcour', 8, 6, NULL),
(76, 'louis', 'perrier', 'Chablais', 'Ollon', 12, 1, NULL),
(77, 'nicole', 'perrin', 'Jura', 'Provence', 8, 9, NULL),
(78, 'claudette', 'perusset', 'Jura', 'Baulmes', 5, 9, NULL),
(79, 'philippe', 'kaltenrieder', 'Broye-Vully', 'Oleyres', 13, 0, NULL),
(80, 'pierre-yves', 'jost', 'Broye-Vully', 'Avenches', 6, 0, NULL),
(81, 'philippe', 'pilloud', 'Nord Vaudois', 'Belmont-sur-Yverdon', 5, 4, NULL),
(82, 'roger', 'pouly', 'Lavaux', 'Savigny', 5, 1, NULL),
(83, 'andré', 'pousaz', 'Chablais', 'Ollon', 9, 1, NULL),
(84, 'olivier', 'rapin', 'Payerne', 'Corcelles pres Payerne', 9, 6, NULL),
(85, 'cédric', 'renaud', 'Nyon', 'Le Vaud', 5, 3, NULL),
(86, 'philippe', 'rochat', 'Morges', 'Chavannes-le-Veyron', 16, 2, NULL),
(87, 'roger', 'cornuz', 'Broye-Vully', 'Mur', 20, 0, NULL),
(88, 'david', 'rojard', 'Nyon', 'Nyon', 6, 4, NULL),
(89, 'jean-luc', 'sonnay', 'Lavaux', 'Oron', 16, 7, NULL),
(90, 'jean-marc', 'soutter', 'Chablais', 'Aigle', 9, 5, NULL),
(91, 'jean-daniel', 'taillefert', 'Nord Vaudois', 'Fiez', 10, 4, NULL),
(92, 'marcel', 'terrin', 'Broye - Vully', 'Valbroye', 10, 7, NULL),
(93, 'frédéric', 'teuscher', 'Joux', 'Vallorbe', 11, 8, NULL),
(94, 'edmond', 'thierrin', 'Broye - Vully', 'Valbroye', 11, 0, NULL),
(95, 'remy', 'turrian', 'Enhaut', 'Rougemont', 8, 5, NULL),
(96, 'michel', 'vittoni', 'Enhaut', 'Ormont-Dessus', 5, 5, NULL),
(97, 'charles', 'volet', 'Lavaux', 'Chardonne', 16, 1, NULL),
(98, 'andré', 'vonlaufen', 'Joux', 'Vallorbe', 20, 8, NULL),
(99, 'ernest', 'walther', 'Nyon', 'Eysins', 16, 3, NULL),
(100, 'yves', 'martin-décoppet', 'Gros-de-Vaud', 'Bavois', 11, 0, NULL),
(101, 'yves', 'thévoz', 'Broye - Vully', 'Granges-près-Marnand', 8, 0, NULL),
(102, 'norbert', 'chabloz', 'Enhaut', 'Château-d\'Oex', 12, 5, NULL),
(103, 'bryan', 'perrin', 'Morges', 'L\'isle', 13, 0, NULL),
(104, 'michel', 'isoz', 'Enhaut', 'Château-d\'Oex', 2, 5, NULL),
(913, 'hubert', 'abberger', 'bodenseekreis', 'heiligenberg', NULL, NULL, NULL),
(914, 'Martin', 'Bosch', 'bodenseekreis', 'neukirch', NULL, NULL, NULL),
(915, 'josef und sohn', 'brauchle', 'bodenseekreis', 'tettnang', NULL, NULL, NULL),
(916, 'hermann', 'dimmeler', 'bodenseekreis', 'hagnau', NULL, NULL, NULL),
(917, 'tim und hubert', 'einholz', 'bodenseekreis', 'salem', NULL, NULL, NULL),
(918, 'Josef', 'Gierer', 'Schwaben', 'Nonnenhorn', NULL, NULL, NULL),
(919, 'johannes', 'haug', 'Schwaben', 'Nonnenhorn', NULL, NULL, NULL),
(920, 'peter', 'heilig', 'bodenseekreis', 'tettnang', NULL, NULL, NULL),
(921, 'jorg', 'hildebrand', 'bodenseekreis', 'eriskirch', NULL, NULL, NULL),
(922, 'josef', 'hornstein', 'lindau', 'nonnenhorn', NULL, NULL, NULL),
(923, 'roland', 'hornstein', 'schwaben', 'nonnenhorn', NULL, NULL, NULL),
(924, 'sophia', 'kurek', 'schwaben', 'nonnenhorn', NULL, NULL, NULL),
(925, 'Roland', 'Manz', 'Bodenseekreis', 'Immenstaad', NULL, NULL, NULL),
(926, 'sebastian', 'martin', 'bodenseekreis', 'Kressbronn', NULL, NULL, NULL),
(927, 'Gottfried', 'Mayer', 'bodenseekreis', 'uberlingen', NULL, NULL, NULL),
(928, 'albrecht', 'mutschele', 'bodenseekreis', 'uberlingen', NULL, NULL, NULL),
(929, 'Mayer', 'Philip', 'bodenseekreis', 'Meckenbeuren', NULL, NULL, NULL),
(930, 'Bernhard', 'Probst', 'bodenseekreis', 'tettnang', NULL, NULL, NULL),
(931, 'huber', 'rainer', 'bodenseekreis', 'deggenhausertal', NULL, NULL, NULL),
(932, 'Helene', 'Riegger', 'bodensee', 'heiligenberg', NULL, NULL, NULL),
(933, 'Uwe', 'Rolle', 'bodenseekreis', 'deggenhausertal', NULL, NULL, NULL),
(934, 'Margret', 'Schmidt', 'Schwaben', 'Wasserburg', NULL, NULL, NULL),
(935, 'vater und sohn', 'specker', 'bodenseekreis', 'Langenargen', NULL, NULL, NULL),
(936, 'Peter', 'Waibel', 'bodenseekreis', 'deggenhausertal', NULL, NULL, NULL),
(937, 'Jurgen', 'Weishaupt', 'Bodenseekreis', 'Ravensburg', NULL, NULL, NULL),
(938, 'Gerhard', 'Wirth', 'Bodenseekreis', 'Friedrichshafen', NULL, NULL, NULL),
(942, 'cédric', 'papaux', 'Broye/ 1534 Sassel ', 'Valbroye / sassel', 3, 0, 'papaux@bluewin.ch'),
(943, 'u', 'test_pour_filtres', 'Morbihan', 'Noyal', NULL, NULL, NULL),
(945, 'emmanuel', 'piot', 'Gros-de-Vaud', '1410 Thierrens', 2, 0, 'emmanuel.piot@gmail.com'),
(946, 'pierre-andré', 'besson', 'Yverdon', 'Yvonand', 1, 0, 'pabessonline@bluewin.ch'),
(947, 'fred & nicolas', 'association walther', 'Morges', 'Pampigny', 7, 0, 'fred_walther@bluewin.ch'),
(948, 'christian', 'hockenjos', 'La Haute Broye ', 'Palézieux', 3, 0, 'cihockenjos@bluewin.ch'),
(949, 'test', 'test', '', '', NULL, NULL, NULL),
(950, 'liliane', 'rochat', 'Yverdon', 'Cuarny', 3, 0, 'liliane@equinet.ch'),
(951, 'laurent', 'gentil', 'Broye', 'Villars-Bramard', 4, 0, 'laugen@bluewin.ch'),
(952, 'patrick', 'sordet', 'jura nord vaudois', 'Bretonnières', 7, 0, 'sordet_patrick@hotmail.com'),
(953, 'dominique', 'jan', 'Broye-Vully', 'Corcelles-près-Payerne', 6, 0, 'jandominique@bluewin.ch'),
(954, 'claude', 'besson', 'Broye-Vully', 'Vully-les-Lacs', 4, 0, 'c.m.besson@bluewin.ch'),
(955, 'eric', 'pavillard', 'Morges', 'Orny', 1, 0, 'eric.pavillard@bluewin.ch'),
(956, 'gaël', 'pavillard', 'Morges', 'Senarclens', 1, 0, 'gael.pavillard@bluewin.ch'),
(957, 'Olivier', 'Guichard', NULL, 'Orzens', NULL, NULL, NULL),
(959, 'philippe', 'magnenat', 'Nord Vaudois', 'Suchy', 13, 0, 'magnenatph@netplus.ch'),
(960, 'stéphane', 'sandoz', 'Jura NV', 'Concise', 6, 0, 'sandoz@lalance.ch'),
(961, 'Yves & Fabien', 'coeytaux', 'morges', 'ballens', 15, 0, 'facoeytaux@hotmail.com'),
(962, 'Jonas', 'Dubois', '', 'Cully', 1, 0, ''),
(964, 'Robert', 'Bovet', 'Morges', 'Vullierens', 1, 0, 'rudolf.steiner@lafermeencroix.ch'),
(966, 'Albert', 'Meyer', 'Broye-Vully', 'Vulliens', 2, 0, 'titi.paty@bluewin.ch'),
(967, 'Sylvain', 'Jacot', 'Gros-de-Vaud', 'Essertines-sur-Yverdon', 3, 0, 'jacot-syl@hotmail.com'),
(968, 'Nicolas', 'Boudry', 'Lavaux', 'Ecoteaux', 3, 0, 'nicolas.boudry@bluewin.ch'),
(969, 'Loïc', 'Miauton', 'Broye - Vully', 'Oleyres', 4, 0, 'loic.miauton@bluewin.ch'),
(970, 'Johann', 'Indermuehle', 'Broye - Vully', 'Cerniaz', 4, 0, 'johanninder@bluewin.ch'),
(971, 'Ferme', 'Des-sources', 'Broye - Vully', 'Grandcour', 4, 0, 'cusin.charles@bluewin.ch'),
(973, 'Swen', 'Piaget', 'Nyon', 'Longirod', 7, 0, 'lavuagere@hotmail.com'),
(974, 'Jean-Luc', 'André', 'Morges', 'yens', 10, 0, 'jlandre@worldcom.ch'),
(975, 'Comm', 'Perey', 'Morges', 'Vufflens-le-Château', 10, 0, 'info@vins-perey.ch'),
(976, 'Frédéric', 'Monnard', 'Morges', 'Berolle', 12, 0, 'fredriderch@bluewin.ch'),
(977, 'Alexandre', 'Collet', 'Gros-de-Vaud', 'Essertines-sur-Yverdon', 13, 0, 'alex.collet@bluewin.ch'),
(978, 'Jean-Marc', 'Freymond-Magnin', 'Morges', 'Montricher', 15, 0, 'Famillefreymond@bluewin.ch'),
(979, 'Dominique', 'Decrausaz', 'Jura Vaudois', 'Vuiteboeuf', 15, 0, 'decrausaz.d@gmail.com'),
(981, 'Johnny', 'Thierstein', 'Jura Vaudois', 'Ste-Croix', 15, 0, 'jhonny.t@bluewin.ch'),
(982, 'elodie', 'freymond', 'Morges', 'Montricher', NULL, NULL, NULL),
(983, 'marc david', 'ramel', 'Pays-d\'enHaut', 'Château-d\'Oex', 6, 0, ''),
(984, 'pascal', 'cusin', 'Payerne', 'Grandcour', 4, 0, '');